# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x9a\x01\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\x12-\n\ttimestamp\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x11\n\tsender_ip\x18\x03 \x01(\t\x12\x13\n\x0bsender_name\x18\x04 \x01(\t\x12\x13\n\x0breceiver_ip\x18\x05 \x01(\t\x12\x15\n\rreceiver_name\x18\x06 \x01(\t\"\x07\n\x05\x45mpty2Y\n\x0b\x43hatService\x12!\n\x0bSendMessage\x12\x08.Message\x1a\x06.Empty\"\x00\x12\'\n\x0fReceiveMessages\x12\x06.Empty\x1a\x08.Message\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGE']._serialized_start=48
  _globals['_MESSAGE']._serialized_end=202
  _globals['_EMPTY']._serialized_start=204
  _globals['_EMPTY']._serialized_end=211
  _globals['_CHATSERVICE']._serialized_start=213
  _globals['_CHATSERVICE']._serialized_end=302
# @@protoc_insertion_point(module_scope)
